"""
LLM Doctor - Evaluation Question Bank

PRIMARY_SET         : 200 samples used for Tables 3, 4, 5 in the paper.
REAL_WORLD_SET      : 30 samples used for the secondary real-world evaluation.

Each entry is {"question": ..., "ground_truth": ...}.

All ground-truth answers are condensed directly from the two source PDFs
(GALE Encyclopedia of Medicine 2nd ed., and Current Essentials of Medicine,
4th ed.) which are the RAG corpus for the LLM Doctor system.
"""

PRIMARY_SET = [
    # ===================================================================
    # SECTION 1: Basic Physiology & General Concepts (1-20)
    # ===================================================================
    {"question": "What is normal body temperature?", "ground_truth": "Normal body temperature averages 37°C (98.6°F). It varies slightly with time of day, activity, and age, but remains tightly regulated by hypothalamic control."},
    {"question": "What is blood pressure?", "ground_truth": "Blood pressure is the force exerted by circulating blood on arterial walls, expressed as systolic over diastolic pressure, reflecting cardiac output and vascular resistance."},
    {"question": "What is hypertension?", "ground_truth": "Hypertension is a chronic condition where blood pressure persistently exceeds 140/90 mmHg, increasing risk of heart disease, stroke, kidney damage, and other complications."},
    {"question": "What is hemoglobin?", "ground_truth": "Hemoglobin is an iron-containing protein in red blood cells responsible for transporting oxygen from lungs to tissues and returning carbon dioxide to lungs."},
    {"question": "What is anemia?", "ground_truth": "Anemia is a condition characterized by reduced hemoglobin or red blood cells, leading to decreased oxygen delivery, causing fatigue, weakness, pallor, and shortness of breath."},
    {"question": "What is heart rate?", "ground_truth": "Heart rate is the number of heartbeats per minute. Normal resting rate in adults ranges from 60 to 100 beats per minute."},
    {"question": "What is myocardial infarction?", "ground_truth": "Myocardial infarction occurs when blood flow to heart muscle is blocked, causing tissue death due to oxygen deprivation, commonly known as a heart attack."},
    {"question": "What is angina pectoris?", "ground_truth": "Angina is chest discomfort caused by reduced blood supply to heart muscle, often triggered by exertion or stress, relieved by rest or medication."},
    {"question": "What is atherosclerosis?", "ground_truth": "Atherosclerosis is buildup of fatty plaques in arteries, narrowing them and reducing blood flow, increasing risk of heart attack, stroke, and peripheral vascular disease."},
    {"question": "What is respiration?", "ground_truth": "Respiration is the process of inhaling oxygen and exhaling carbon dioxide, involving lungs and blood circulation to maintain cellular metabolism and energy production."},
    {"question": "What is asthma?", "ground_truth": "Asthma is a chronic inflammatory disease of airways causing reversible narrowing, leading to wheezing, breathlessness, chest tightness, and coughing, especially at night or early morning."},
    {"question": "What is pneumonia?", "ground_truth": "Pneumonia is infection of lung tissue causing inflammation of alveoli, often filled with fluid or pus, resulting in fever, cough, difficulty breathing, and chest pain."},
    {"question": "What is hypoxia?", "ground_truth": "Hypoxia is a condition where body tissues receive insufficient oxygen, leading to cellular dysfunction and potential organ damage if prolonged or severe."},
    {"question": "What is digestion?", "ground_truth": "Digestion is the process of breaking down food into smaller molecules for absorption and use by the body, involving mechanical and chemical processes."},
    {"question": "What is gastritis?", "ground_truth": "Gastritis is inflammation of stomach lining caused by infection, stress, alcohol, or drugs, leading to pain, nausea, vomiting, and possible bleeding."},
    {"question": "What is jaundice?", "ground_truth": "Jaundice is yellow discoloration of skin and eyes due to increased bilirubin levels, often caused by liver disease, bile duct obstruction, or hemolysis."},
    {"question": "What is diarrhea?", "ground_truth": "Diarrhea is frequent passage of loose or watery stools, commonly due to infection, food intolerance, or gastrointestinal disorders, leading to dehydration and electrolyte imbalance."},
    {"question": "What is constipation?", "ground_truth": "Constipation is infrequent or difficult bowel movements, often caused by low fiber intake, dehydration, or reduced physical activity, leading to discomfort and straining."},
    {"question": "What is neuron?", "ground_truth": "Neuron is the basic functional unit of nervous system responsible for transmitting electrical and chemical signals between different parts of body."},
    {"question": "What is stroke?", "ground_truth": "Stroke occurs when blood supply to part of brain is interrupted or reduced, causing brain cell death and leading to neurological deficits like paralysis or speech loss."},

    # ===================================================================
    # SECTION 2: Neurology & Endocrine (21-40)
    # ===================================================================
    {"question": "What is epilepsy?", "ground_truth": "Epilepsy is a neurological disorder characterized by recurrent seizures due to abnormal electrical activity in brain, affecting consciousness, movement, or behavior."},
    {"question": "What is reflex action?", "ground_truth": "Reflex action is an automatic, rapid response to a stimulus without conscious control, mediated through spinal cord pathways for protection and quick reaction."},
    {"question": "What is coma?", "ground_truth": "Coma is a prolonged state of unconsciousness where a person cannot be awakened and does not respond to stimuli due to severe brain dysfunction."},
    {"question": "What is hormone?", "ground_truth": "Hormones are chemical messengers secreted by endocrine glands that regulate body functions such as growth, metabolism, reproduction, and homeostasis."},
    {"question": "What is diabetes mellitus?", "ground_truth": "Diabetes mellitus is a metabolic disorder characterized by high blood glucose levels due to insufficient insulin production or impaired insulin action."},
    {"question": "What is insulin?", "ground_truth": "Insulin is a hormone produced by pancreas that regulates blood glucose by facilitating uptake of glucose into cells for energy and storage."},
    {"question": "What is hyperthyroidism?", "ground_truth": "Hyperthyroidism is condition where thyroid gland produces excess hormones, increasing metabolism, causing weight loss, rapid heartbeat, nervousness, and heat intolerance."},
    {"question": "What is hypothyroidism?", "ground_truth": "Hypothyroidism is condition of reduced thyroid hormone production, leading to slowed metabolism, fatigue, weight gain, cold intolerance, and depression."},
    {"question": "What is a migraine headache?", "ground_truth": "Migraine is a recurrent throbbing headache, often unilateral, lasting 4-72 hours, associated with nausea, vomiting, photophobia, and phonophobia, sometimes preceded by an aura."},
    {"question": "What is Parkinson's disease?", "ground_truth": "Parkinson's disease is a progressive neurological disorder characterized by tremor, rigidity, bradykinesia, and postural instability due to loss of dopamine-producing neurons."},
    {"question": "What is multiple sclerosis?", "ground_truth": "Multiple sclerosis is a chronic autoimmune disease affecting the central nervous system, causing demyelination of nerve fibers with episodic neurological deficits."},
    {"question": "What is myasthenia gravis?", "ground_truth": "Myasthenia gravis is an autoimmune disorder of the neuromuscular junction causing fatigable muscle weakness, particularly of eye, face, and swallowing muscles."},
    {"question": "What is meningitis?", "ground_truth": "Meningitis is inflammation of the membranes surrounding the brain and spinal cord, causing fever, headache, neck stiffness, and altered mental status."},
    {"question": "What is Bell's palsy?", "ground_truth": "Bell's palsy is an idiopathic acute unilateral facial nerve paralysis causing weakness of the forehead, difficulty closing the eye, and loss of taste on the anterior tongue."},
    {"question": "What is a transient ischemic attack?", "ground_truth": "A transient ischemic attack (TIA) is a temporary episode of neurological dysfunction caused by reduced blood flow to the brain, resolving within 24 hours without permanent damage."},
    {"question": "What is Guillain-Barré syndrome?", "ground_truth": "Guillain-Barré syndrome is an acute inflammatory polyneuropathy causing progressive ascending symmetric muscle weakness, often preceded by an infection, with areflexia."},
    {"question": "What is trigeminal neuralgia?", "ground_truth": "Trigeminal neuralgia is a condition characterized by sudden, severe, lancinating facial pain in the distribution of the trigeminal nerve, often triggered by touch or eating."},
    {"question": "What is Huntington's disease?", "ground_truth": "Huntington's disease is an autosomal dominant neurodegenerative disorder causing progressive chorea and dementia, due to a CAG trinucleotide repeat expansion on chromosome 4."},
    {"question": "What is normal pressure hydrocephalus?", "ground_truth": "Normal pressure hydrocephalus is a disorder characterized by the triad of gait apraxia, urinary incontinence, and dementia, with enlarged ventricles on imaging but normal opening pressure on lumbar puncture."},
    {"question": "What is a syringomyelia?", "ground_truth": "Syringomyelia is a condition in which a fluid-filled cavity forms in the spinal cord, causing cape-like loss of pain and temperature sensation, weakness, and atrophy."},

    # ===================================================================
    # SECTION 3: Cardiovascular (41-60)
    # ===================================================================
    {"question": "What is Cardiac Tamponade?", "ground_truth": "Life-threatening disorder occurring when pericardial fluid accumulates under pressure; effusions rapidly increasing in size may cause an elevated intrapericardial pressure."},
    {"question": "What defines Cor Pulmonale?", "ground_truth": "Heart failure resulting from pulmonary disease. Most commonly due to COPD; other causes include pulmonary fibrosis, pneumoconioses, recurrent pulmonary emboli."},
    {"question": "What is acute pericarditis?", "ground_truth": "Acute pericarditis is inflammation of the pericardium causing pleuritic chest pain that improves with sitting up, often accompanied by a friction rub and diffuse ST elevation on ECG."},
    {"question": "What is constrictive pericarditis?", "ground_truth": "Constrictive pericarditis is a condition in which a thickened, fibrotic pericardium impairs cardiac filling, causing symptoms of right heart failure such as ascites and edema."},
    {"question": "What is congestive heart failure?", "ground_truth": "Congestive heart failure is a condition in which the heart cannot pump enough blood to meet the body's needs, causing symptoms of dyspnea, fatigue, and fluid retention."},
    {"question": "What is dilated cardiomyopathy?", "ground_truth": "A cause of systolic dysfunction, this represents a group of disorders that lead to congestive heart failure. Symptoms and signs of congestive heart failure: Exertional dyspnea, cough, fatigue, paroxysmal nocturnal dyspnea."},
    {"question": "What is hypertrophic cardiomyopathy?", "ground_truth": "Hypertrophic cardiomyopathy is an asymmetric myocardial hypertrophy causing dynamic obstruction to left ventricular outflow, potentially causing dyspnea, syncope, and sudden cardiac death."},
    {"question": "What is restrictive cardiomyopathy?", "ground_truth": "Restrictive cardiomyopathy is characterized by impaired diastolic filling with preserved left ventricular function, often caused by amyloidosis, sarcoidosis, or hemochromatosis."},
    {"question": "What is mitral regurgitation?", "ground_truth": "Mitral regurgitation is a valvular heart disease where the mitral valve fails to close properly, causing a blowing pansystolic murmur and possible heart failure."},
    {"question": "What is mitral stenosis?", "ground_truth": "Mitral stenosis is a valvular heart disease, almost always caused by rheumatic heart disease, causing dyspnea, a low-pitched diastolic murmur, and an opening snap."},
    {"question": "What is aortic stenosis?", "ground_truth": "Aortic stenosis is a narrowing of the aortic valve causing dyspnea, angina, and syncope, with a harsh systolic ejection murmur radiating to the neck and pulsus parvus et tardus."},
    {"question": "What is aortic regurgitation?", "ground_truth": "Aortic regurgitation is a valvular heart disease causing a decrescendo diastolic murmur, wide pulse pressure, and heart failure over time."},
    {"question": "What is acute coronary syndrome?", "ground_truth": "Acute coronary syndrome is a spectrum of conditions including unstable angina, non-ST elevation MI, and ST elevation MI, caused by acute myocardial ischemia."},
    {"question": "What is unstable angina?", "ground_truth": "Unstable angina is a form of acute coronary syndrome characterized by accelerating angina, pain at rest, or pain less responsive to medications, usually due to atherosclerotic plaque rupture."},
    {"question": "What is Prinzmetal's angina?", "ground_truth": "Prinzmetal's angina is chest pain caused by intermittent focal spasm of an otherwise normal coronary artery, typically occurring at rest and associated with ST elevation."},
    {"question": "What is atrial fibrillation?", "ground_truth": "Atrial fibrillation is the most common chronic arrhythmia, characterized by an irregularly irregular heartbeat due to disorganized atrial electrical activity, with risk of embolization."},
    {"question": "What is atrial flutter?", "ground_truth": "Atrial flutter is an arrhythmia with an atrial rate of 250-350 beats per minute, often seen with COPD, causing a characteristic sawtooth pattern on ECG."},
    {"question": "What is ventricular tachycardia?", "ground_truth": "Ventricular tachycardia is a wide-complex tachycardia of three or more consecutive ventricular beats, potentially life-threatening, especially with structural heart disease."},
    {"question": "What is paroxysmal supraventricular tachycardia?", "ground_truth": "PSVT is a group of arrhythmias including AV nodal reentrant and AV reentrant tachycardias, characterized by sudden onset and termination of rapid regular narrow-complex tachycardia."},
    {"question": "What is a heart block?", "ground_truth": "Heart block refers to delayed or blocked conduction of electrical impulses through the AV node, classified as first-degree, second-degree (Mobitz I/II), or third-degree (complete) block."},

    # ===================================================================
    # SECTION 4: Respiratory (61-80)
    # ===================================================================
    {"question": "What is acute bacterial pneumonia?", "ground_truth": "Acute bacterial pneumonia is an infection of the lungs causing fever, chills, cough with purulent sputum, and patchy or lobar infiltrates on chest x-ray."},
    {"question": "What is atypical pneumonia?", "ground_truth": "Atypical pneumonia is pneumonia caused by organisms like Legionella, Mycoplasma, and Chlamydia, with scant sputum, prominent systemic symptoms, and patchy infiltrates."},
    {"question": "What is pulmonary embolism?", "ground_truth": "Pulmonary embolism is the blockage of a pulmonary artery by a blood clot, usually originating from a deep vein thrombosis, causing sudden dyspnea, chest pain, and hypoxemia."},
    {"question": "What is acute respiratory distress syndrome?", "ground_truth": "ARDS is a rapid-onset respiratory failure with diffuse alveolar infiltrates, severe hypoxemia refractory to oxygen, and a PaO2/FiO2 ratio less than 200."},
    {"question": "What is chronic obstructive pulmonary disease?", "ground_truth": "COPD is a chronic lung disease including emphysema and chronic bronchitis, characterized by progressive airflow obstruction, primarily caused by smoking."},
    {"question": "What is chronic bronchitis?", "ground_truth": "Chronic bronchitis is a form of COPD defined by a productive cough for at least three months in two consecutive years, with hypoxemia and hypercapnia."},
    {"question": "What is emphysema?", "ground_truth": "Emphysema is a form of COPD characterized by destruction of alveolar walls, causing loss of lung elasticity, hyperinflation, and decreased diffusing capacity."},
    {"question": "What is bronchiectasis?", "ground_truth": "Bronchiectasis is a congenital or acquired disorder causing permanent abnormal dilation and destruction of bronchial walls, with chronic cough and copious purulent sputum."},
    {"question": "What is cystic fibrosis?", "ground_truth": "Cystic fibrosis is an autosomal recessive disorder of exocrine glands causing thick mucus production, leading to chronic lung infections, pancreatic insufficiency, and malabsorption."},
    {"question": "What is pulmonary tuberculosis?", "ground_truth": "Pulmonary tuberculosis is infection by Mycobacterium tuberculosis causing cough, fever, night sweats, weight loss, and hemoptysis, with apical fibronodular infiltrates on chest film."},
    {"question": "What is sarcoidosis?", "ground_truth": "Sarcoidosis is a disease of unknown cause causing noncaseating granulomas, most commonly affecting the lungs with symmetric hilar adenopathy and interstitial infiltrates."},
    {"question": "What is asbestosis?", "ground_truth": "Asbestosis is interstitial fibrosis of the lungs caused by inhalation of asbestos particles, appearing 20-40 years after exposure, with lower-lung fibrosis and pleural thickening."},
    {"question": "What is silicosis?", "ground_truth": "Silicosis is a chronic fibrotic lung disease caused by inhalation of crystalline silicon dioxide, with bilateral upper lobe fibrosis, nodules, and eggshell calcification of hilar nodes."},
    {"question": "What is sleep apnea?", "ground_truth": "Sleep apnea is a disorder characterized by repeated episodes of apnea during sleep, causing excessive daytime somnolence, morning headache, and increased cardiovascular risk."},
    {"question": "What is a solitary pulmonary nodule?", "ground_truth": "A solitary pulmonary nodule is a round or oval circumscribed lesion less than 3 cm in diameter amid normal lung tissue, which may be benign or malignant."},
    {"question": "What is a spontaneous pneumothorax?", "ground_truth": "Spontaneous pneumothorax is a collapsed lung occurring without trauma, typically in tall thin young men, causing sudden chest pain, dyspnea, and decreased breath sounds."},
    {"question": "What is pleural effusion?", "ground_truth": "Pleural effusion is abnormal accumulation of fluid in the pleural space, which may be transudative (heart failure, cirrhosis) or exudative (malignancy, infection)."},
    {"question": "What is hypersensitivity pneumonitis?", "ground_truth": "Hypersensitivity pneumonitis is an allergic inflammation of the lungs caused by inhalation of organic dusts, with cough, dyspnea, fever, and crackles hours after exposure."},
    {"question": "What is idiopathic pulmonary fibrosis?", "ground_truth": "Idiopathic pulmonary fibrosis is a chronic progressive interstitial lung disease with exertional dyspnea, dry cough, clubbing, and restrictive pattern on pulmonary function tests."},
    {"question": "What is a lung abscess?", "ground_truth": "A lung abscess is a collection of pus within the lung, often caused by aspiration, producing cough with foul-smelling sputum, fever, and a cavity with air-fluid level on imaging."},

    # ===================================================================
    # SECTION 5: Gastrointestinal & Hepatobiliary (81-105)
    # ===================================================================
    {"question": "What is achalasia?", "ground_truth": "Achalasia is an esophageal motility disorder characterized by failure of the lower esophageal sphincter to relax and absent peristalsis, causing progressive dysphagia."},
    {"question": "What is Barrett's esophagus?", "ground_truth": "Barrett's esophagus is replacement of the normal squamous epithelium of the esophagus with columnar epithelium, a complication of chronic GERD with increased risk of adenocarcinoma."},
    {"question": "What is benign esophageal stricture?", "ground_truth": "Benign esophageal stricture is a narrowing of the esophagus causing dysphagia for solids more than liquids, often a late complication of chronic reflux or other esophageal injury."},
    {"question": "What is celiac sprue?", "ground_truth": "Celiac sprue is an immune-mediated disorder triggered by dietary gluten, causing malabsorption, steatorrhea, weight loss, and villous atrophy of the small intestine."},
    {"question": "What is Crohn's disease?", "ground_truth": "Crohn's disease is an inflammatory bowel disease characterized by insidious onset of diarrhea, right lower quadrant pain, and skip lesions with transmural inflammation."},
    {"question": "What is ulcerative colitis?", "ground_truth": "Ulcerative colitis is an inflammatory bowel disease with contiguous colonic involvement from the rectum, causing bloody diarrhea, urgency, and tenesmus."},
    {"question": "What is irritable bowel syndrome?", "ground_truth": "Irritable bowel syndrome is a chronic functional disorder with abdominal pain associated with altered bowel habits, without identifiable organic pathology."},
    {"question": "What is a duodenal ulcer?", "ground_truth": "Duodenal ulcer is an ulcer of the duodenum caused mostly by Helicobacter pylori or NSAIDs, causing epigastric pain relieved by food or antacids."},
    {"question": "What is a gastric ulcer?", "ground_truth": "Gastric ulcer is an ulcer of the stomach causing epigastric pain, weight loss, and possible bleeding; endoscopic biopsy is required to exclude malignancy."},
    {"question": "What is gastroesophageal reflux disease?", "ground_truth": "GERD is a condition in which stomach contents reflux into the esophagus, causing substernal burning (pyrosis) aggravated by recumbency and relieved by sitting up."},
    {"question": "What is acute pancreatitis?", "ground_truth": "Acute pancreatitis is inflammation of the pancreas, usually from alcohol or gallstones, causing epigastric pain radiating to the back with elevated serum amylase and lipase."},
    {"question": "What is chronic pancreatitis?", "ground_truth": "Chronic pancreatitis is progressive inflammation and fibrosis of the pancreas, causing chronic abdominal pain, maldigestion, diabetes, and pancreatic calcification."},
    {"question": "What is Mallory-Weiss syndrome?", "ground_truth": "Mallory-Weiss syndrome is a mucosal laceration of the gastroesophageal junction after forceful vomiting, causing hematemesis of bright red blood."},
    {"question": "What is a colonic polyp?", "ground_truth": "A colonic polyp is a discrete mass lesion arising from the colonic epithelium protruding into the lumen, potentially precancerous if adenomatous."},
    {"question": "What is Zollinger-Ellison syndrome?", "ground_truth": "Zollinger-Ellison syndrome is a gastrinoma causing severe recurrent peptic ulcer disease, with fasting serum gastrin greater than 150 pg/mL and diarrhea."},
    {"question": "What is Clostridium difficile colitis?", "ground_truth": "Clostridium difficile colitis is a pseudomembranous colitis causing profuse watery diarrhea with cramping, often after antibiotic use, with fecal leukocytes present."},
    {"question": "What is acute liver failure?", "ground_truth": "Acute liver failure is severe liver injury in a person with previously normal liver function, with hepatic encephalopathy and impaired synthetic function."},
    {"question": "What is acute viral hepatitis?", "ground_truth": "Acute viral hepatitis is inflammation of the liver caused by hepatitis viruses, causing jaundice, fever, tender hepatomegaly, and elevated aminotransferases."},
    {"question": "What is alcoholic hepatitis?", "ground_truth": "Alcoholic hepatitis is acute liver inflammation caused by heavy alcohol use, with fever, jaundice, tender hepatomegaly, and AST typically elevated but rarely above 300 U/L."},
    {"question": "What is cirrhosis?", "ground_truth": "Cirrhosis is a chronic degenerative disease in which normal liver cells are damaged and replaced by scar tissue, causing impaired liver function and portal hypertension."},
    {"question": "What is autoimmune hepatitis?", "ground_truth": "Autoimmune hepatitis is a chronic inflammatory liver disease, usually affecting young women, with elevated aminotransferases, polyclonal gammopathy, and autoantibodies."},
    {"question": "What is primary biliary cirrhosis?", "ground_truth": "Primary biliary cirrhosis is a chronic cholestatic liver disease, usually affecting women aged 40-60, with pruritus, jaundice, and positive antimitochondrial antibody."},
    {"question": "What is hemochromatosis?", "ground_truth": "Hemochromatosis is a genetic disorder causing excessive intestinal iron absorption with parenchymal deposition, resulting in cirrhosis, diabetes, and heart failure."},
    {"question": "What is Wilson's disease?", "ground_truth": "Wilson's disease is an autosomal recessive disorder of copper metabolism causing hepatic and neuropsychiatric dysfunction, with Kayser-Fleischer rings in the cornea."},
    {"question": "What is hepatic encephalopathy?", "ground_truth": "Hepatic encephalopathy is a spectrum of neurologic and psychiatric abnormalities resulting from liver dysfunction, ranging from mild confusion to coma."},

    # ===================================================================
    # SECTION 6: Hematologic (106-120)
    # ===================================================================
    {"question": "What is acute leukemia?", "ground_truth": "Acute leukemia is a malignancy with rapid onset of fever, weakness, bleeding, and pancytopenia with circulating leukemic blasts greater than 20% in marrow or blood."},
    {"question": "What is chronic lymphocytic leukemia?", "ground_truth": "CLL is a chronic leukemia with sustained lymphocytosis greater than 5000/microliter, morphologically mature cells, lymphadenopathy, and splenomegaly."},
    {"question": "What is chronic myelogenous leukemia?", "ground_truth": "CML is a myeloproliferative disorder characterized by the Philadelphia chromosome t(9;22), causing marked leukocytosis, splenomegaly, and progression to acute leukemia."},
    {"question": "What is hairy cell leukemia?", "ground_truth": "Hairy cell leukemia is a rare chronic leukemia with pancytopenia, prominent splenomegaly, and characteristic hairy cells on peripheral smear; marrow aspiration often yields a dry tap."},
    {"question": "What is multiple myeloma?", "ground_truth": "Multiple myeloma is a malignancy of plasma cells causing bone pain, lytic bone lesions, anemia, renal insufficiency, and monoclonal protein in serum or urine."},
    {"question": "What is Hodgkin's disease?", "ground_truth": "Hodgkin's disease is a lymphoma characterized by Reed-Sternberg cells and orderly contiguous spread, usually presenting with painless cervical lymphadenopathy."},
    {"question": "What is non-Hodgkin's lymphoma?", "ground_truth": "Non-Hodgkin's lymphoma is a group of lymphoid malignancies with fever, night sweats, weight loss, and variable hepatosplenomegaly and lymphadenopathy."},
    {"question": "What is aplastic anemia?", "ground_truth": "Aplastic anemia is a condition of pancytopenia with hypocellular bone marrow and fatty infiltration, causing fatigue, pallor, purpura, and infection risk."},
    {"question": "What is iron deficiency anemia?", "ground_truth": "Iron deficiency anemia is anemia due to low iron, causing hypochromic microcytic red cells, low serum ferritin, and occult blood loss as the usual cause in adults."},
    {"question": "What is vitamin B12 deficiency?", "ground_truth": "Vitamin B12 deficiency causes megaloblastic anemia with oval macrocytes, hypersegmented neutrophils, and neurologic symptoms including paresthesias and dementia."},
    {"question": "What is folic acid deficiency?", "ground_truth": "Folic acid deficiency causes megaloblastic anemia with oval macrocytes and hypersegmented neutrophils, but without the neurologic symptoms seen in B12 deficiency."},
    {"question": "What is thalassemia major?", "ground_truth": "Thalassemia major is severe anemia from infancy with hypochromic microcytic cells, poikilocytosis, target cells, and greatly elevated hemoglobin F levels."},
    {"question": "What is sickle cell anemia?", "ground_truth": "Sickle cell anemia is a hemoglobinopathy with a valine-for-glutamine substitution on the beta chain, causing recurrent pain crises, jaundice, and functional asplenia."},
    {"question": "What is disseminated intravascular coagulation?", "ground_truth": "DIC is a consumptive coagulopathy with abnormal bleeding or clotting, thrombocytopenia, prolonged PT, low fibrinogen, and elevated fibrin degradation products."},
    {"question": "What is heparin-induced thrombocytopenia?", "ground_truth": "HIT is a disorder with moderate thrombocytopenia 4-14 days after starting heparin, with paradoxical thrombosis and positive antiheparin-PF4 antibodies."},

    # ===================================================================
    # SECTION 7: Infectious Diseases (121-145)
    # ===================================================================
    {"question": "What is infection?", "ground_truth": "Infection occurs when microorganisms like bacteria, viruses, or fungi invade body tissues, multiply, and cause disease by damaging cells or triggering immune responses."},
    {"question": "What is immunity?", "ground_truth": "Immunity is the body's ability to resist infections through defense mechanisms including physical barriers, immune cells, and antibodies that recognize and eliminate pathogens."},
    {"question": "What is vaccination?", "ground_truth": "Vaccination is the process of administering weakened or inactive pathogens to stimulate immune response, providing protection against specific infectious diseases."},
    {"question": "What is antibiotic?", "ground_truth": "Antibiotics are drugs used to treat bacterial infections by killing bacteria or inhibiting their growth, but they are ineffective against viral infections."},
    {"question": "What is virus?", "ground_truth": "Virus is a microscopic infectious agent that requires host cells to replicate, causing diseases by invading cells and disrupting their normal functions."},
    {"question": "What is Candidiasis?", "ground_truth": "Candidiasis is an infection caused by a species of the yeast Candida, usually Candida albicans. This is a common cause of vaginal infections in women."},
    {"question": "What is tetanus?", "ground_truth": "Tetanus is caused by Clostridium tetani, causing jaw stiffness followed by spasms (trismus), muscle stiffness, dysphagia, irritability, and hyperreflexia, with late painful convulsions."},
    {"question": "What is tuberculosis?", "ground_truth": "Tuberculosis is caused by Mycobacterium tuberculosis, with symptoms that are progressive and include cough, dyspnea, fever, night sweats, weight loss, and hemoptysis."},
    {"question": "What is anthrax?", "ground_truth": "Anthrax is caused by Bacillus anthracis, presenting with a persistent necrotic ulcer on exposed surfaces, regional adenopathy, and possible hemorrhagic mediastinitis from inhaled spores."},
    {"question": "What is botulism?", "ground_truth": "Botulism is caused by Clostridium botulinum toxin, causing cranial nerve paralysis, diplopia, dry mouth, dysphagia, dysphonia, and progressive symmetric muscle weakness."},
    {"question": "What is brucellosis?", "ground_truth": "Brucellosis is an infection acquired from animal exposure or unpasteurized dairy, causing insidious fever, diaphoresis, anorexia, fatigue, headache, back pain, and lymphadenopathy."},
    {"question": "What is cholera?", "ground_truth": "Cholera is caused by Vibrio cholerae, causing acute watery diarrhea with massive fluid loss leading to profound hypovolemia, characterized by rice-water stool."},
    {"question": "What is diphtheria?", "ground_truth": "Diphtheria is an acute infection by Corynebacterium diphtheriae causing sore throat, a tenacious gray membrane at the portal of entry, and toxin-induced myocarditis or neuropathy."},
    {"question": "What is gonorrhea?", "ground_truth": "Gonorrhea is a common sexually transmitted disease caused by Neisseria gonorrhoeae, causing purulent urethral discharge in men and often asymptomatic infection in women."},
    {"question": "What is Legionnaires' disease?", "ground_truth": "Legionnaires' disease is pneumonia caused by Legionella pneumophila, with malaise, fever, headache, pleuritic chest pain, and patchy infiltrates on chest x-ray."},
    {"question": "What is leprosy?", "ground_truth": "Leprosy is a chronic infection by Mycobacterium leprae, causing pale anesthetic macular or infiltrative erythematous skin lesions, with superficial nerve thickening."},
    {"question": "What is leptospirosis?", "ground_truth": "Leptospirosis is transmitted by exposure to water or soil contaminated by animal urine, causing abrupt high fever, headache, myalgias, conjunctival injection, and jaundice."},
    {"question": "What is Lyme disease?", "ground_truth": "Lyme disease is caused by Borrelia burgdorferi from Ixodes ticks, with erythema migrans, flulike symptoms, and potential neurologic, cardiac, and joint manifestations."},
    {"question": "What is meningococcal meningitis?", "ground_truth": "Meningococcal meningitis is caused by Neisseria meningitidis, causing fever, headache, vomiting, confusion, and a petechial or ecchymotic rash with possible DIC."},
    {"question": "What is pertussis?", "ground_truth": "Pertussis is caused by Bordetella pertussis, causing a catarrhal stage followed by paroxysmal cough ending in a high-pitched inspiratory whoop, with marked lymphocytosis."},
    {"question": "What is plague?", "ground_truth": "Plague is caused by Yersinia pestis, transmitted by rodent fleas, causing sudden high fever, severe malaise, myalgias, and regional lymphadenitis with suppuration."},
    {"question": "What is psittacosis?", "ground_truth": "Psittacosis is caused by Chlamydophila psittaci, transmitted from birds, causing rapid onset of fever, chills, headache, dry cough, and pneumonitis on chest x-ray."},
    {"question": "What is salmonellosis?", "ground_truth": "Salmonella gastroenteritis is caused by various Salmonella species, causing nausea, headache, fever, high-volume diarrhea, and abdominal pain 8-72 hours after contaminated food ingestion."},
    {"question": "What is Staphylococcus aureus toxic shock syndrome?", "ground_truth": "Staph toxic shock syndrome is associated with tampon use or surgery, with abrupt fever, vomiting, diarrhea, toxic appearance, diffuse rash, and hypotension."},
    {"question": "What is streptococcal pharyngitis?", "ground_truth": "Streptococcal pharyngitis is caused by group A beta-hemolytic streptococci, causing abrupt sore throat, fever, pharyngeal exudate, cervical adenopathy, and possible scarlet fever."},

    # ===================================================================
    # SECTION 8: Fungal, Protozoal, Helminthic (146-160)
    # ===================================================================
    {"question": "What is cryptococcosis?", "ground_truth": "Cryptococcosis is an opportunistic infection caused by Cryptococcus neoformans, most commonly causing meningitis in AIDS or immunocompromised patients."},
    {"question": "What is histoplasmosis?", "ground_truth": "Histoplasmosis is caused by Histoplasma capsulatum, often asymptomatic but causing cough, fever, malaise in self-limited infections, and disseminated disease in immunocompromised."},
    {"question": "What is coccidioidomycosis?", "ground_truth": "Coccidioidomycosis is caused by Coccidioides immitis from desert soil, causing fever, pleuritis, dry cough, erythema nodosum, and arthralgias, known as valley fever."},
    {"question": "What is pneumocystis pneumonia?", "ground_truth": "Pneumocystis pneumonia is caused by Pneumocystis jiroveci, seen primarily in immunocompromised patients with CD4 less than 200, causing fever, dyspnea, and diffuse alveolar infiltrates."},
    {"question": "What is sporotrichosis?", "ground_truth": "Sporotrichosis is caused by Sporothrix schenckii from plant or soil exposure, causing nodules along lymphatic drainage with possible ulceration and black eschar."},
    {"question": "What is amebiasis?", "ground_truth": "Amebiasis is infection of the large intestine by Entamoeba histolytica, causing recurrent diarrhea, abdominal cramps, and possible liver abscess."},
    {"question": "What is giardiasis?", "ground_truth": "Giardiasis is infection of the upper small intestine by Giardia lamblia, causing acute or chronic diarrhea with bulky greasy stools, abdominal discomfort, and malabsorption."},
    {"question": "What is malaria?", "ground_truth": "Malaria is caused by Plasmodium species, causing paroxysms of periodic chills, fever, headache, myalgias, and sweating, with anemia and splenomegaly."},
    {"question": "What is toxoplasmosis?", "ground_truth": "Toxoplasmosis is caused by Toxoplasma gondii, usually mild in immunocompetent hosts, but causing brain abscess in immunocompromised patients and congenital infection."},
    {"question": "What is Chagas' disease?", "ground_truth": "Chagas' disease is caused by Trypanosoma cruzi from reduviid bugs, with acute phase often asymptomatic and chronic phase causing cardiac arrhythmias and megaesophagus or megacolon."},
    {"question": "What is visceral leishmaniasis?", "ground_truth": "Visceral leishmaniasis (kala-azar) is caused by Leishmania donovani from sandfly bites, causing irregular fever with progressive skin darkening, cachexia, and marked splenomegaly."},
    {"question": "What is ascariasis?", "ground_truth": "Ascariasis is caused by Ascaris lumbricoides, with a pulmonary phase causing cough and eosinophilia, and an intestinal phase causing vague abdominal discomfort and possible obstruction."},
    {"question": "What is echinococcosis?", "ground_truth": "Echinococcosis (hydatid disease) is a zoonosis from dog tapeworm larvae, causing avascular cystic tumors of liver, lung, or brain with possible anaphylaxis on rupture."},
    {"question": "What is enterobiasis?", "ground_truth": "Enterobiasis is pinworm infection by Enterobius vermicularis, causing nocturnal perianal pruritus, insomnia, and restlessness, most commonly in children."},
    {"question": "What is schistosomiasis?", "ground_truth": "Schistosomiasis is caused by Schistosoma species, with acute Katayama fever and chronic sequelae including portal hypertension (S. mansoni) or hematuria (S. haematobium)."},

    # ===================================================================
    # SECTION 9: Rheumatology & Autoimmune (161-175)
    # ===================================================================
    {"question": "What is rheumatoid arthritis?", "ground_truth": "Rheumatoid arthritis is a symmetric inflammatory polyarthritis of peripheral joints, causing morning stiffness, joint deformity, and extra-articular manifestations."},
    {"question": "What is systemic lupus erythematosus?", "ground_truth": "SLE is a multisystem autoimmune disease principally affecting young women, with malar rash, photosensitivity, arthritis, serositis, and renal involvement."},
    {"question": "What is ankylosing spondylitis?", "ground_truth": "Ankylosing spondylitis is a seronegative spondyloarthropathy causing gradual back pain in young adults, with bilateral sacroiliitis and characteristic bamboo spine on x-ray."},
    {"question": "What is gout?", "ground_truth": "Gout is a crystal-induced arthritis caused by deposition of monosodium urate crystals, classically causing nocturnal podagra (first MTP joint) pain, tophi, and hyperuricemia."},
    {"question": "What is pseudogout?", "ground_truth": "Pseudogout is calcium pyrophosphate dihydrate deposition disease causing subacute recurrent arthritis of large joints with chondrocalcinosis on x-ray."},
    {"question": "What is Behçet's syndrome?", "ground_truth": "Behçet's syndrome is a vasculitis usually in young adults from Mediterranean or Japanese ancestry, with recurrent painful oral and genital ulcers, uveitis, and skin lesions."},
    {"question": "What is fibromyalgia?", "ground_truth": "Fibromyalgia is a chronic syndrome of widespread muscle pain and stiffness, with multiple tender points, fatigue, and nonrestorative sleep, without objective inflammation."},
    {"question": "What is polymyalgia rheumatica?", "ground_truth": "Polymyalgia rheumatica is an inflammatory condition in patients over 50, with morning stiffness of shoulder and hip girdles, elevated ESR, and dramatic response to low-dose prednisone."},
    {"question": "What is giant cell arteritis?", "ground_truth": "Giant cell arteritis is a large-vessel vasculitis often coexisting with polymyalgia rheumatica, causing headache, jaw claudication, and risk of irreversible vision loss."},
    {"question": "What is scleroderma?", "ground_truth": "Systemic sclerosis (scleroderma) is a chronic connective tissue disease causing skin thickening and fibrosis, with limited (CREST) or diffuse forms affecting internal organs."},
    {"question": "What is Sjögren's syndrome?", "ground_truth": "Sjögren's syndrome is a chronic autoimmune disorder with destruction of exocrine glands, causing dry mouth and dry eyes (sicca symptoms) and possible systemic involvement."},
    {"question": "What is polyarteritis nodosa?", "ground_truth": "Polyarteritis nodosa is a systemic vasculitis of medium-sized arteries, causing fever, hypertension, abdominal pain, and possible association with hepatitis B."},
    {"question": "What is Wegener's granulomatosis?", "ground_truth": "Wegener's granulomatosis is a vasculitis with glomerulonephritis and necrotizing granulomas of upper and lower respiratory tracts, associated with C-ANCA."},
    {"question": "What is dermatomyositis?", "ground_truth": "Dermatomyositis is an inflammatory myopathy with symmetric proximal muscle weakness, heliotrope rash, Gottron's papules, and increased risk of associated malignancy."},
    {"question": "What is Takayasu's arteritis?", "ground_truth": "Takayasu's arteritis is a large-vessel vasculitis involving the aortic arch and branches, most common in women aged 20-40, with absent pulses and vascular insufficiency."},

    # ===================================================================
    # SECTION 10: Dermatologic (176-190)
    # ===================================================================
    {"question": "What characterizes Tinea Versicolor?", "ground_truth": "Finely scaling patches on upper trunk and upper arms, usually asymptomatic. Lesions yellowish or brownish on pale skin, or hypopigmented on dark skin."},
    {"question": "What characterizes Urticaria (Hives)?", "ground_truth": "Pale or red, evanescent, edematous papules or plaques surrounded by red halo with severe itching or stinging; wheals appear suddenly and resolve in hours."},
    {"question": "What characterizes Vitiligo?", "ground_truth": "Depigmented white patches surrounded by a normal, hyperpigmented, or occasionally inflamed border. Hairs in affected area usually turn white."},
    {"question": "What is acne vulgaris?", "ground_truth": "Acne vulgaris is a common disorder of the pilosebaceous unit with open and closed comedones, papules, pustules, and nodules, occurring at puberty and often persisting into adulthood."},
    {"question": "What is atopic dermatitis?", "ground_truth": "Atopic dermatitis is a chronic pruritic inflammatory skin disease, often starting in infancy, associated with a personal or family history of atopy, asthma, or allergic rhinitis."},
    {"question": "What is psoriasis?", "ground_truth": "Psoriasis is a chronic inflammatory skin disease with well-demarcated silvery-scaled plaques on extensor surfaces, associated with psoriatic arthritis in a subset of patients."},
    {"question": "What is seborrheic dermatitis?", "ground_truth": "Seborrheic dermatitis is a chronic inflammatory condition with greasy, scaly, yellowish patches on the scalp, face, and other sebaceous areas; in infants it is called cradle cap."},
    {"question": "What is basal cell carcinoma?", "ground_truth": "Basal cell carcinoma is the most common skin cancer, appearing as a pearly papule with telangiectasias or a rolled-border plaque, locally invasive but rarely metastatic."},
    {"question": "What is squamous cell carcinoma?", "ground_truth": "Squamous cell carcinoma is a skin cancer arising from sun-damaged skin, appearing as a hyperkeratotic, indurated papule or plaque that may ulcerate and metastasize."},
    {"question": "What is melanoma?", "ground_truth": "Melanoma is the most serious skin cancer, evaluated by ABCDE criteria: Asymmetry, Border irregularity, Color variation, Diameter over 6mm, and Evolving changes."},
    {"question": "What is actinic keratosis?", "ground_truth": "Actinic keratosis is a precancerous skin lesion from chronic sun exposure, appearing as discrete keratotic scaly papules on face, ears, scalp, and dorsal hands."},
    {"question": "What is scabies?", "ground_truth": "Scabies is a pruritic skin condition caused by the Sarcoptes scabiei mite, with intense nocturnal itching and burrows in finger webs, wrists, and genital areas."},
    {"question": "What is pediculosis?", "ground_truth": "Pediculosis is lice infestation; head lice cause scalp pruritus and nits on hair, body lice cause generalized pruritus, and pubic lice (crabs) are usually sexually transmitted."},
    {"question": "What is impetigo?", "ground_truth": "Impetigo is a superficial skin infection with rapidly spreading erythema, vesicles, or golden-crusted lesions, most commonly caused by streptococci or staphylococci."},
    {"question": "What is herpes zoster?", "ground_truth": "Herpes zoster (shingles) is a reactivation of varicella-zoster virus, causing painful vesicular rash in a dermatomal distribution, with possible postherpetic neuralgia."},

    # ===================================================================
    # SECTION 11: Renal & Genitourinary (191-200)
    # ===================================================================
    {"question": "What is acute cystitis?", "ground_truth": "Acute cystitis is infection of the bladder causing dysuria, frequency, urgency, hematuria, and suprapubic pain, usually caused by gram-negative bacteria such as E. coli."},
    {"question": "What is pyelonephritis?", "ground_truth": "Acute pyelonephritis is infection of the kidney and renal pelvis causing fever, flank pain, and vomiting, with pyuria, bacteriuria, and white cell casts in urine."},
    {"question": "What is nephrotic syndrome?", "ground_truth": "Nephrotic syndrome is characterized by proteinuria over 3 g/day, hypoalbuminemia, edema, and hyperlipidemia, with hypercoagulability and possible renal vein thrombosis."},
    {"question": "What is acute glomerulonephritis?", "ground_truth": "Acute glomerulonephritis is inflammation of the glomeruli, often following streptococcal infection, causing hematuria with red cell casts, proteinuria, and hypertension."},
    {"question": "What is acute kidney injury?", "ground_truth": "Acute kidney injury is an abrupt decline in kidney function, commonly caused by acute tubular necrosis, with oliguria, rising creatinine, and electrolyte abnormalities."},
    {"question": "What is chronic kidney disease?", "ground_truth": "Chronic kidney disease is progressive loss of kidney function over months to years, classified by GFR stages I-V, with complications including anemia, bone disease, and acidosis."},
    {"question": "What is benign prostatic hyperplasia?", "ground_truth": "BPH is nonmalignant enlargement of the prostate causing urinary hesitancy, weak stream, nocturia, and urgency, with possible urinary retention and azotemia."},
    {"question": "What is testicular torsion?", "ground_truth": "Testicular torsion is twisting of the spermatic cord causing sudden severe unilateral scrotal pain, with an asymmetric high-riding testis and absence of cremasteric reflex."},
    {"question": "What is kidney stones (urolithiasis)?", "ground_truth": "Urinary calculi are stones in the urinary tract causing sudden severe flank pain radiating to the groin, hematuria in 90%, nausea, and vomiting."},
    {"question": "What is bacterial prostatitis?", "ground_truth": "Bacterial prostatitis is infection of the prostate, with acute form causing fever, dysuria, perineal pain, and tender prostate, and chronic form causing recurrent urinary symptoms."},

    # ===================================================================
    # SECTION 12: Oncology & Misc (201-...)
    # ===================================================================
    {"question": "What is breast cancer in women?", "ground_truth": "Breast cancer typically presents as a painless lump with possible nipple or skin changes; axillary lymph node involvement is the most powerful prognostic indicator."},
    {"question": "What is colorectal carcinoma?", "ground_truth": "Colorectal carcinoma causes altered bowel habits, rectal bleeding, and iron deficiency anemia; risk factors include colonic polyposis, Lynch syndrome, and ulcerative colitis."},
    {"question": "What is lung cancer?", "ground_truth": "Lung cancer is the most common cause of cancer death, with smoking as the most important cause; it can present with cough, hemoptysis, or as an asymptomatic mass."},
    {"question": "What is prostate cancer?", "ground_truth": "Prostate cancer is a common malignancy in older men, often asymptomatic, with a hard irregular prostate on exam and elevated PSA; bone metastases may be present."},
    {"question": "What is cervical cancer?", "ground_truth": "Cervical cancer is associated with human papillomavirus in almost all cases, presenting with abnormal uterine bleeding, vaginal discharge, or pelvic pain."},
    {"question": "What is hepatocellular carcinoma?", "ground_truth": "Hepatocellular carcinoma is a common visceral malignancy, often in patients with hepatitis B or C cirrhosis, with abdominal enlargement, pain, jaundice, and elevated alpha-fetoprotein."},
    {"question": "What is gastric carcinoma?", "ground_truth": "Gastric carcinoma presents with abdominal pain, dyspepsia, anorexia, weight loss, and iron deficiency anemia; risk factors include H. pylori and atrophic gastritis."},
    {"question": "What is pancreatic cancer?", "ground_truth": "Pancreatic cancer typically presents with upper abdominal pain radiating to the back, weight loss, and painless jaundice, with most tumors in the head of the pancreas."},
    {"question": "What is ovarian cancer?", "ground_truth": "Ovarian cancer may present with abdominal distention, pelvic pain, and vaginal bleeding; CA 125 is useful for monitoring recurrence but not for screening."},
    {"question": "What is testicular cancer?", "ground_truth": "Testicular cancer most often presents as a painless testicular nodule in men aged 20-35, with tumor markers AFP, LDH, and beta-hCG used for diagnosis and monitoring."},
    {"question": "What is thyroid cancer?", "ground_truth": "Thyroid cancer presents as a hard, painless thyroid nodule that does not regress with thyroid hormone; papillary carcinoma has the best prognosis."},
    {"question": "What is bladder cancer?", "ground_truth": "Bladder cancer commonly presents with microscopic or gross hematuria without other symptoms; risk factors include smoking and occupational exposure to aromatic amines."},
    {"question": "What is malignant melanoma?", "ground_truth": "Melanoma is a malignancy of melanocytes with high metastatic potential, with risk factors including fair skin, sun exposure, family history, and dysplastic nevi."},
    {"question": "What is a CNS tumor?", "ground_truth": "Central nervous system tumors present with generalized symptoms like nocturnal headache, seizures, and focal deficits related to tumor location; gliomas comprise about half."},
    {"question": "What is multiple endocrine neoplasia?", "ground_truth": "MEN is a group of inherited syndromes causing hyperplasia or tumors of multiple endocrine glands, including MEN1 (parathyroid, pituitary, pancreas) and MEN2 (thyroid, adrenal)."},

    # ===================================================================
    # SECTION 13: Pediatrics, Obstetrics, Toxicology (216-230)
    # ===================================================================
    {"question": "What is croup?", "ground_truth": "Croup is a childhood illness with barking cough, stridor, and hoarseness following an upper respiratory infection, most common between ages 3 months and 5 years."},
    {"question": "What is pyloric stenosis?", "ground_truth": "Pyloric stenosis is hypertrophy of the pylorus in infants causing projectile nonbilious vomiting between 2 and 8 weeks of age, with a palpable olive-like mass."},
    {"question": "What is intussusception?", "ground_truth": "Intussusception is telescoping of one part of the bowel into another, causing intermittent colicky abdominal pain, vomiting, and currant jelly stools, common before age 2."},
    {"question": "What is Kawasaki's disease?", "ground_truth": "Kawasaki's disease is a vasculitis of medium-sized arteries in children under 5, with fever, conjunctivitis, mucositis, rash, and risk of coronary artery aneurysms."},
    {"question": "What is febrile seizure?", "ground_truth": "Febrile seizures occur in children aged 9 months to 5 years, lasting less than 15 minutes, generalized, and occurring in developmentally normal children."},
    {"question": "What is respiratory syncytial virus bronchiolitis?", "ground_truth": "RSV bronchiolitis is a major cause of lower respiratory infection in infants under 1 year, with fever, cough, tachypnea, wheezing, and possible apnea."},
    {"question": "What is colic?", "ground_truth": "Colic is a syndrome of severe paroxysmal crying in infants, usually 1-3 months old, worsening in the late afternoon and evening, with a distended abdomen."},
    {"question": "What is enuresis?", "ground_truth": "Enuresis is involuntary urination at an age when control is expected (around age 5), mostly nocturnal, with 75% having at least one parent with similar history."},
    {"question": "What is ectopic pregnancy?", "ground_truth": "Ectopic pregnancy is implantation of the pregnancy outside the uterine cavity, most commonly in the fallopian tube, causing pelvic pain and bleeding and posing risk of rupture."},
    {"question": "What is pre-eclampsia?", "ground_truth": "Pre-eclampsia is hypertension and proteinuria after 20 weeks of gestation, with severe forms causing headaches, visual changes, and risk of seizures (eclampsia)."},
    {"question": "What is endometriosis?", "ground_truth": "Endometriosis is growth of endometrial tissue outside the uterus, causing cyclic pelvic pain, dysmenorrhea, dyspareunia, and infertility."},
    {"question": "What is acetaminophen poisoning?", "ground_truth": "Acetaminophen toxicity causes acute hepatic failure; N-acetylcysteine is nearly 100% protective if given within 8 hours of ingestion."},
    {"question": "What is carbon monoxide poisoning?", "ground_truth": "Carbon monoxide poisoning causes tissue hypoxia and affects organs with the highest oxygen demand (heart, brain), with nonspecific flulike symptoms, headache, and possible coma."},
    {"question": "What is organophosphate poisoning?", "ground_truth": "Organophosphate poisoning causes cholinergic excess (SLUDGE: salivation, lacrimation, urination, defecation, GI distress, emesis), with miosis, bradycardia, and bronchospasm."},
    {"question": "What is salicylate poisoning?", "ground_truth": "Salicylate poisoning causes mixed respiratory alkalosis and metabolic acidosis, with hyperpnea, tinnitus, confusion, and risk of seizures and pulmonary edema."},
]


REAL_WORLD_SET = [
    # 30 real-world clinical-style queries (paraphrased from MedQuAD-style sources)
    {"question": "A 55-year-old patient presents with crushing chest pain radiating to the left arm. What is the most likely diagnosis?",
     "ground_truth": "Myocardial infarction (heart attack) is the most likely diagnosis. It occurs when blood flow to the heart muscle is blocked by a coronary artery occlusion, causing tissue death from oxygen deprivation."},
    {"question": "A patient has a blood pressure of 150/95 mmHg on two separate visits. How should this be classified?",
     "ground_truth": "This is Stage 1 hypertension. Hypertension is defined as persistent blood pressure above 140/90 mmHg."},
    {"question": "What is the first-line treatment for anaphylaxis?",
     "ground_truth": "Intramuscular epinephrine (adrenaline) is the first-line treatment for anaphylaxis, followed by airway support and antihistamines."},
    {"question": "A diabetic patient presents with fruity breath, nausea, and confusion. What complication should be suspected?",
     "ground_truth": "Diabetic ketoacidosis (DKA) should be suspected, characterized by hyperglycemia, ketosis, and metabolic acidosis."},
    {"question": "What is the classic triad of symptoms for meningitis?",
     "ground_truth": "The classic triad is fever, neck stiffness, and altered mental status. Headache and photophobia are also common."},
    {"question": "A patient on long-term steroids abruptly stops the medication. What is the risk?",
     "ground_truth": "Adrenal crisis may occur due to suppressed adrenal function. Steroids must be tapered gradually."},
    {"question": "What is the recommended initial management for a suspected stroke?",
     "ground_truth": "Immediate assessment with CT to distinguish ischemic from hemorrhagic stroke, followed by thrombolysis (within 4.5 hours for ischemic stroke) if eligible."},
    {"question": "Which electrolyte abnormality causes peaked T waves on ECG?",
     "ground_truth": "Hyperkalemia (elevated serum potassium) causes peaked T waves, widened QRS, and can progress to cardiac arrest."},
    {"question": "A patient with COPD presents with worsening dyspnea and purulent sputum. What is the likely diagnosis?",
     "ground_truth": "Acute exacerbation of COPD, often triggered by respiratory infection. Requires bronchodilators, steroids, and possibly antibiotics."},
    {"question": "What is the most common cause of community-acquired pneumonia?",
     "ground_truth": "Streptococcus pneumoniae is the most common cause of community-acquired pneumonia."},
    {"question": "A child presents with barking cough and inspiratory stridor. What is the likely diagnosis?",
     "ground_truth": "Croup (laryngotracheobronchitis), usually caused by parainfluenza virus. Managed with corticosteroids and sometimes nebulized epinephrine."},
    {"question": "What is the treatment for a patient with suspected opioid overdose?",
     "ground_truth": "Naloxone (Narcan) is the antidote for opioid overdose, reversing respiratory depression."},
    {"question": "A patient reports sudden severe headache described as 'worst of my life'. What should be suspected?",
     "ground_truth": "Subarachnoid hemorrhage (SAH) from a ruptured cerebral aneurysm should be suspected. Requires urgent CT and possibly lumbar puncture."},
    {"question": "What is the most common cause of peptic ulcer disease?",
     "ground_truth": "Helicobacter pylori infection, followed by NSAID use, are the most common causes of peptic ulcer disease."},
    {"question": "How is acute appendicitis typically diagnosed?",
     "ground_truth": "Clinical presentation (periumbilical pain migrating to right lower quadrant, anorexia, nausea), Alvarado score, ultrasound or CT imaging."},
    {"question": "A patient on warfarin has an INR of 6.0 without bleeding. What is the management?",
     "ground_truth": "Hold warfarin, consider oral vitamin K (phytonadione) for INR 4.5-10 without bleeding. If bleeding, use prothrombin complex concentrate."},
    {"question": "What are the classic symptoms of hypothyroidism?",
     "ground_truth": "Fatigue, weight gain, cold intolerance, constipation, dry skin, bradycardia, and depression."},
    {"question": "A patient presents with polyuria, polydipsia, and polyphagia. What is the likely diagnosis?",
     "ground_truth": "Diabetes mellitus. The classic triad reflects hyperglycemia causing osmotic diuresis, thirst, and cellular starvation."},
    {"question": "What is the immediate management of a patient with acute asthma exacerbation?",
     "ground_truth": "Supplemental oxygen, inhaled short-acting beta-agonists (albuterol), systemic corticosteroids, and possibly ipratropium."},
    {"question": "What is the most common cause of cirrhosis in the Western world?",
     "ground_truth": "Chronic alcohol abuse is the most common cause of cirrhosis in the Western world; viral hepatitis (B and C) is the most common worldwide."},
    {"question": "A patient has a positive Homans sign and unilateral leg swelling. What is the likely diagnosis?",
     "ground_truth": "Deep vein thrombosis (DVT). Confirmed with Doppler ultrasound; treated with anticoagulation."},
    {"question": "What are the warning signs of melanoma?",
     "ground_truth": "The ABCDE criteria: Asymmetry, Border irregularity, Color variation, Diameter > 6mm, Evolving changes."},
    {"question": "What is the treatment of choice for acute gout?",
     "ground_truth": "NSAIDs, colchicine, or corticosteroids for acute attacks. Urate-lowering therapy (allopurinol, febuxostat) for chronic management."},
    {"question": "A patient with heart failure has an ejection fraction of 30%. How is this classified?",
     "ground_truth": "Heart failure with reduced ejection fraction (HFrEF). EF < 40% defines HFrEF; 40-49% is HFmrEF; > 50% is HFpEF."},
    {"question": "What is the classic presentation of acute pancreatitis?",
     "ground_truth": "Severe epigastric pain radiating to the back, nausea, vomiting, and elevated serum lipase/amylase."},
    {"question": "What is the immediate management of a tension pneumothorax?",
     "ground_truth": "Needle decompression in the second intercostal space, midclavicular line, followed by chest tube insertion."},
    {"question": "What are the risk factors for osteoporosis?",
     "ground_truth": "Female sex, advanced age, postmenopausal estrogen deficiency, low calcium/vitamin D, smoking, alcohol, sedentary lifestyle, and long-term corticosteroid use."},
    {"question": "A patient has a low TSH and elevated free T4. What is the diagnosis?",
     "ground_truth": "Primary hyperthyroidism. Low TSH reflects feedback suppression from excess thyroid hormone."},
    {"question": "What is the recommended screening interval for colonoscopy in average-risk adults?",
     "ground_truth": "Every 10 years starting at age 45 for average-risk adults, per current guidelines."},
    {"question": "What is the management of a patient with suspected meningitis?",
     "ground_truth": "Immediate blood cultures, empiric IV antibiotics (e.g., ceftriaxone + vancomycin), and dexamethasone before or with the first antibiotic dose. Lumbar puncture when safe."},
]